### ISSUE TITLE
Autogenerated md file needs to link to https://nextstrain.org/rsv/a/genome rather than https://nextstrain.org/rsv/A/genome

### ISSUE THREAD

**Issue by corneliusroemer** [rsv-lineages/lineage-designation-A#1]
I noticed that the link from "View in Nextstrain" here: https://github.com/rsv-lineages/lineage-designation-A/blob/main/.auto-generated/clades.md goes to https://nextstrain.org/rsv/A/genome which doesn't work as it has a capital A rather than lower case a

I'm not sure where the auto-generation script lives, it doesn't seem to be in the repo (yet). A working link needs to start with https://nextstrain.org/rsv/a/genome unless we make a`A` -> `a` redirect on nextstrain.org

I think Richard @rneher has the auto-generation script somewhere.

The same issue applies to the RSV-B repo.

**Comment by rneher** [comment]
thanks. that is indeed an issue in my script/workflow.

**Comment by rneher** [comment]
should be resolved in 9a85e5086bcfb516fb6b3a3bcc255a8696359b25
